#!/bin/bash

QTD=10000

[ -n "$1" ] && QTD=$1

FILE=tests/linhas_venda_$QTD.txt

if [[ ! -f $FILE ]]; then
  for i in $(seq 1 "$QTD"); do
    echo "$(($RANDOM % $QTD + 1)) $(($RANDOM % $QTD + 1)) $(($RANDOM % $QTD + 1))" >>"$FILE"
  done
fi
